language: c

compiler:
  - gcc
  - clang

os:
  - linux

env:
  - ARCH=x86_64
  - ARCH=i386

cache:
  - apt

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
    then
      sudo apt-get update -qq;
      if [ "$ARCH" = "x86_64" ];
      then
        sudo apt-get install -qq libusb-1.0-0-dev;
      elif [ "$ARCH" = "i386" ];
      then
        sudo apt-get install -qq gcc-multilib libusb-1.0-0-dev:i386 pkg-config:i386;
        export CFLAGS="-m32";
      fi
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];
    then
      brew update;
      brew install libusb;
    fi

before_script:
  - mkdir build && cd build

script:
  - cmake ../ && make

before_deploy:
  - export RELEASE_NAME=libcyusbserial-$TRAVIS_TAG-$TRAVIS_OS_NAME-$ARCH
  - cd -
  - mkdir -p $RELEASE_NAME/{include,lib,tools}
  - cp ./COPYING.LESSER.txt ./README.md $RELEASE_NAME/
  - cp ./include/*.h $RELEASE_NAME/include/
  - cp ./build/lib/*.so{,.*} $RELEASE_NAME/lib/
  - cp ./build/tools/cyusbserialtest ./tools/README.txt $RELEASE_NAME/tools/
  - tar -czf $RELEASE_NAME.tar.gz $RELEASE_NAME

deploy:
  provider: releases
  api_key:
    secure: eYzcv257okDxTohG7njLqRMIjad9ytsxsE0ORqvYBaQRYlOUuG8LXlj7JCmABMXvdWXVmaNbJ4k5o0qN8hiINwIarf14TzkXzfaXnZ6oTkQh4+6QWJudbNo1vGUIHV9ax4gUw4cV/UTKnviceNq82LnCHKa4i9Ts4HrQeKjXdEw=
  file: $RELEASE_NAME.tar.gz
  on:
    repo: cyrozap/libcyusbserial
    tags: true
    all_branches: true
    condition: "$CC = gcc"
